parameters:
    database_driver: pdo_sqlite
    database_host: localhost
    database_port: null
    database_name: qacfp
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 4e45dd6c86d168e21ed785b961539017
    database_path: app/data/database.sqlite
