qafoo_cfp_homepage:
    pattern:  /
    defaults: { _controller: QafooCfpBundle:Default:index }

qafoo_cfp_new:
    pattern:  /cfp/new
    defaults: { _controller: QafooCfpBundle:Default:new }

qafoo_cfp_new_success:
    pattern: /cfp/{cfpId}/success
    defaults: { _controller: QafooCfpBundle:Default:success }
