parameters:
#    qafoo_cfp.example.class: Qafoo\CfpBundle\Example

services:
#    qafoo_cfp.example:
#        class: %qafoo_cfp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
